name: DoorDash_part1

on:
  push:
    branches: 
     - "main"
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout_repository
        uses: actions/checkout@v6

      - name: build_docker_image
        run: |
          docker build -t doordash/delivery-fee-service .

      - name: run_docker
        run: |
          docker run -d --name fee-service -p 8080:8080 doordash/delivery-fee-service

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be ready on http://localhost:8080 ..."
          for i in {1..10}; do
            if curl -sSf http://localhost:8080/status/ > /dev/null; then
              echo "API is up ✅"
              exit 0
            fi
            echo "API not ready yet, retrying in 3s..."
            sleep 5
          done
          echo "API failed to start ❌"
          docker logs fee-service || true
          exit 1

      - name : install_test_dependencies
        run : |
          pip install pytest httpx

      - name : run_tests
        run : |
          pytest -v

      - name: Stop and remove container
        if: always()
        run: |
          docker stop fee-service || true
          docker rm fee-service || true
          docker ps -a
