name: DoorDash_part1

on:
  push:
    branches: 
     - "main"
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout_repository
        uses: actions/checkout@v6

      - name: build_docker_image
        run: |
          docker build -t doordash/delivery-fee-service .

      - name: run_docker
        run: |
          docker run -d -p 8080:8080 doordash/delivery-fee-service

      - name : status_endpoint
        run : |
          curl -sSf http://localhost:8080/status/ || exit 1

      - name: Stop and remove container
        if: always()
        run: |
          docker stop fee-service || true
          docker rm fee-service || true
          docker ps -a
